### ISSUE TITLE
微信支付回调异常

### ISSUE THREAD

**Issue by wanghao0807** [Pay-Group/best-pay-sdk#12]
如果使用了微信支付到店红包会导致回调失败，不使用这种红包就一切正常
![image](https://user-images.githubusercontent.com/18650761/37594466-2a09ba1a-2bb0-11e8-9f8a-cbef6b2a6c4b.png)

**Comment by 1005423557** [comment]
同问

**Comment by lly835** [comment]
测试过了，新版已修复了这个bug
https://github.com/Pay-Group/best-pay-sdk/releases/tag/1.3.0.BETA
