### ISSUE TITLE
微信支付验证签名失败,有使用红包的时候验证都是失败的

### ISSUE THREAD

**Issue by 1005423557** [Pay-Group/best-pay-sdk#13]
微信支付验证签名失败,有使用红包的时候验证都是失败的

**Comment by lly835** [comment]
红包怎么来的，想测试一下

**Comment by lly835** [comment]
测试过了，新版已修复了这个bug
https://github.com/Pay-Group/best-pay-sdk/releases/tag/1.3.0.BETA
