### ISSUE TITLE
	fix bug: 元转分使用double丢失精度, 应先转成String

### ISSUE THREAD

**Issue by HugoIT** [Pay-Group/best-pay-sdk#15]
fix bug: 元转分使用double丢失精度, 应先转成String
但是直接用maven依赖：
<dependency>
     <groupId>cn.springboot</groupId>
     <artifactId>best-pay-sdk</artifactId>
     <version>1.1.0</version>
</dependency>

**Comment by HugoIT** [comment]
还是之前的元转分版本，不是最新的，请问如何解决

**Comment by ghoolooloo** [comment]
我也遇到这个问题，金额为0.03时，结果被转换成了0.02。为什么不使用整数表示金额了，单位为分？

**Comment by steven-ma** [comment]
> 我也遇到这个问题，金额为0.03时，结果被转换成了0.02。为什么不使用整数表示金额了，单位为分？

其实我们在生产中也遇到了这个问题，本来是用best-pay-sdk准备投产的，后来很多系统特别是金融系统，我们都是用分为单位的整数（Long/Integer)，在转换的时候担心会转在精度损失（而且微信本来的接口也是整数，不过微信有点奇怪：统一下单用的是分，对账文件用的是元 -_-），就换了别的SDK，为了保持原先本来的兼容，要不看看后面再实现多个接口吧，采用整数。 @lly835

**Comment by lly835** [comment]
@steven-ma 用分不太好，有些系统，计算利率，2位小数肯定不够用，还是用decimal最好

**Comment by lly835** [comment]
这个bug：1.2.0已修复
