### ISSUE TITLE
使用代金券支付，异步通知回调验证签名异常

### ISSUE THREAD

**Issue by HugoIT** [Pay-Group/best-pay-sdk#17]
建议使用微信官方的：WXPayUtil.isSignatureValid(notifyData, key);

**Comment by lly835** [comment]
用的是哪种代金券，怎么获取代金券

**Comment by lly835** [comment]
测试过了，新版已修复了这个bug
https://github.com/Pay-Group/best-pay-sdk/releases/tag/1.3.0.BETA
