### ISSUE TITLE
best-pay-sdk依赖tomcat，导致使用其他容器会有冲突

### ISSUE THREAD

**Issue by ghoolooloo** [Pay-Group/best-pay-sdk#22]
我的spring boot项目采用undertow容器，而不是默认的tomcat容器。结果在使用websocket过程中，老是报错。后面发现，原来best-pay-sdk有依赖tomcat容器。切换回tomcat就正常了。
一个支付的sdk为什么要绑死tomcat呢？

**Comment by lly835** [comment]
sdk没有依赖tomcat
