### ISSUE TITLE
微信退款带异步通知的接口，新版本可以使用吗？

### ISSUE THREAD

**Issue by yitiaoluoyuo** [Pay-Group/best-pay-sdk#23]
近期开发项目时需要退款申请后，需要接受到微信的异步通知，老师1.1版本里没有这个接口。就上来看看，我看到老师近期提交的有【新增微信加解密-退款通知，未测试】字眼，请问老师这个功能可以使用了吗？

**Comment by lly835** [comment]
目前还没有

**Comment by lly835** [comment]
同 https://github.com/Pay-Group/best-pay-sdk/issues/28
