### ISSUE TITLE
最近有XXE攻击，忘引起重视

### ISSUE THREAD

**Issue by liuxianzhong** [Pay-Group/best-pay-sdk#25]
修复方案：
XmlUtil.java
line 65:
            Map<String, String> data = new HashMap<>();
            DocumentBuilderFactory documentBuilderFactory = DocumentBuilderFactory.newInstance();
            //防止xxe攻击
            documentBuilderFactory.setExpandEntityReferences(false);

            String FEATURE = null;
            try {
                FEATURE = "http://apache.org/xml/features/disallow-doctype-decl";
                documentBuilderFactory.setFeature(FEATURE, true);
                FEATURE = "http://xml.org/sax/features/external-general-entities";
                documentBuilderFactory.setFeature(FEATURE, false);
                FEATURE = "http://xml.org/sax/features/external-parameter-entities";
                documentBuilderFactory.setFeature(FEATURE, false);
                documentBuilderFactory.setXIncludeAware(false);
                documentBuilderFactory.setExpandEntityReferences(false);
            } catch ( Exception e) {
                logger.info("微信异步通知解析文件出错：原因：{}" + ExcepitonUitl.printErrorTrace(e) );
                e.printStackTrace();
            }

            DocumentBuilder documentBuilder = documentBuilderFactory.newDocumentBuilder();
            InputStream stream = new ByteArrayInputStream(strXML.getBytes("UTF-8"));
            org.w3c.dom.Document doc = documentBuilder.parse(stream);
            doc.getDocumentElement().normalize();
            NodeList nodeList = doc.getDocumentElement().getChildNodes();

....................

**Comment by MRLWB** [comment]
有没有已经修改好打包成jar包的呢，急用，谢谢了！

**Comment by MRLWB** [comment]
或者说完整的XMLUtil.java代码文件，有没有反编译jar，打包的软件

**Comment by MRLWB** [comment]
万分感谢

**Comment by 52844895** [comment]
同求,万分感谢

**Comment by 52844895** [comment]
@MRLWB 兄弟,你解决了吗?

**Comment by lly835** [comment]
我这没用那个框架
