### ISSUE TITLE
微信 NATIVE 扫码支付 是不是没实现

### ISSUE THREAD

**Issue by bei123wang** [Pay-Group/best-pay-sdk#26]
/**
     * H5支付交易类型选择
     */
    public String switchH5TradeType(BestPayTypeEnum payTypeEnum){
        String tradeType = "JSAPI";
        switch (payTypeEnum){
            case WXPAY_H5:
                tradeType = "JSAPI";
                break;
            case WXPAY_MWEB:
                tradeType = "MWEB";
                break;
        }
        return tradeType;
    }

**Comment by lly835** [comment]
新版本已实现 https://github.com/Pay-Group/best-pay-sdk/releases/tag/1.3.0.BETA
