### ISSUE TITLE
问一下，现在这个sdk还没有关闭微信订单的功能吗

### ISSUE THREAD

**Issue by XuDing806011875** [Pay-Group/best-pay-sdk#32]

**Comment by DevilAndBird** [comment]
问一下如果10月25号不调整微信支付的漏洞就会被关闭微信支付功能么？

**Comment by XuDing806011875** [comment]
不会，微信只会完善支付功能，支付这么重要的功能不会关闭的。。

**Comment by 52844895** [comment]
> 问一下如果10月25号不调整微信支付的漏洞就会被关闭微信支付功能么？

兄弟,我的项目里面商户号也收到这个XXE支付漏洞处理通知: "为保证用户资金安全，微信支付将于2018年10月25日对仍未修复的商户采取暂停交易权限的措施" , 请问怎么解决???

**Comment by 52844895** [comment]
@DevilAndBird 我的项目里面商户号也收到这个XXE支付漏洞处理通知: "为保证用户资金安全，微信支付将于2018年10月25日对仍未修复的商户采取暂停交易权限的措施" , 请问你解决了吗???

**Comment by lly835** [comment]
你说的关闭订单是微信哪个接口
