### ISSUE TITLE
希望增加微信pc扫码支付

### ISSUE THREAD

**Issue by lly835** [Pay-Group/best-pay-sdk#41]
https://pay.weixin.qq.com/wiki/doc/api/native.php?chapter=6_1

**Comment by tmlx1990** [comment]
扫码支付的话，规划还是使用统一的入口吗？

**Comment by tmlx1990** [comment]
> https://pay.weixin.qq.com/wiki/doc/api/native.php?chapter=6_1

扫码支付的话，规划还是使用统一的入口吗？

**Comment by lly835** [comment]
> > https://pay.weixin.qq.com/wiki/doc/api/native.php?chapter=6_1
> 
> 扫码支付的话，规划还是使用统一的入口吗？

是的，使用方式依旧简单，只要修改支付方式即可

```
PayRequest payRequest = new PayRequest();
 payRequest.setPayTypeEnum(BestPayTypeEnum.WXPAY_H5);
 payRequest.setOrderId("123456");
 payRequest.setOrderName("微信公众账号支付订单");
 payRequest.setOrderAmount(0.01);
 payRequest.setOpenid("openid_xxxxxx");
 bestPayService.pay(payRequest);
```
