### ISSUE TITLE
关于best-pay-sdk

### ISSUE THREAD

**Issue by Scounderal** [Pay-Group/best-pay-sdk#5]
就把demo里面的三个java文件拷过来了，然后配置文件自己建了个.properties文件，除了读取配置文件，其他代码都没动

**Comment by lly835** [comment]
什么意思？请描述具体问题

**Comment by Scounderal** [comment]
可能我不太会表述，抱歉啊，就是我的项目是springmvc的，而你这个demo是用的springboot，那肯定是要改些地方对吧，比如读取配置文件就不能用@ConfigurationProperties(prefix = "wechat")，这种方式了吧，其他地方倒是没改，但是启动项目一直提示@Autowired private BestPayServiceImpl bestPayService;注入这个BestPayServiceImpl 错误，可能还有哪里配置不对，可能还没描述清楚，你多担待，那个群是怎么加的啊，订单号是哪个啊

**Comment by lly835** [comment]
群号就在项目主页，加群不需要订单号，听你描述下来，应该不是sdk的问题，是你的项目搞得不对，引入其他的sdk，也会报错吧。

**Comment by Scounderal** [comment]
好吧，加群了，同意下，方便找你私聊么

**Comment by lly835** [comment]
加的哪个群，没看到

**Comment by Scounderal** [comment]
318333393，这个群，不是么，项目主页里的

**Comment by lly835** [comment]
非sdk问题，关闭
