### ISSUE TITLE
使用H5支付（MWEB类型）时，微信外浏览器如何获取用户的openId？

### ISSUE THREAD

**Issue by youchunze** [Pay-Group/best-pay-sdk#58]

**Comment by lly835** [comment]
这种支付方式，是不需要openid的，请看微信支付官方文档




在2019年10月07日 01:21，youchunze 写道：

**Comment by youchunze** [comment]
> 这种支付方式，是不需要openid的，请看微信支付官方文档 在2019年10月07日 01:21，youchunze 写道： — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

还想请问个事情，我支付成功后，回调/notify方法进不去，看您给的例子http://best-pay.springboot.cn说要自行判断订单状态，意思是不是H5无法回调，要自己去查询订单呢？还是我的回调方法出错了？

**Comment by lly835** [comment]
> 还想请问个事情，我支付成功后，回调/notify方法进不去，看您给的例子[http://best-pay.springboot.cn说要自行判断订单状态，意思是不是H5无法回调，要自己去查询订单呢？还是我的回调方法出错了？

/notify是接收微信异步通知的接口。

**Comment by youchunze** [comment]
> > 还想请问个事情，我支付成功后，回调/notify方法进不去，看您给的例子[http://best-pay.springboot.cn说要自行判断订单状态，意思是不是H5无法回调，要自己去查询订单呢？还是我的回调方法出错了？
> 
> /notify是接收微信异步通知的接口。

我的/notify 使用postman可以访问，但是在支付成功却收不到微信异步通知（进不去debug）。

**Comment by lly835** [comment]
说明传到微信的异步通知地址不正确


 原始邮件 
发件人: youchunze<notifications@github.com>
收件人: Pay-Group/best-pay-sdk<best-pay-sdk@noreply.github.com>
抄送: lly835<lly835@163.com>; Comment<comment@noreply.github.com>
发送时间: 2019年10月12日(周六) 17:30
主题: Re: [Pay-Group/best-pay-sdk] 使用H5支付（MWEB类型）时，微信外浏览器如何获取用户的openId？ (#58)


还想请问个事情，我支付成功后，回调/notify方法进不去，看您给的例子[http://best-pay.springboot.cn说要自行判断订单状态，意思是不是H5无法回调，要自己去查询订单呢？还是我的回调方法出错了？
/notify是接收微信异步通知的接口。
我的/notify 使用postman可以访问，但是在支付成功却收不到微信异步通知（进不去debug）。

**Comment by lly835** [comment]
已经可以体验了 http://best-pay.springboot.cn
你也可以看看项目的源码

**Comment by youchunze** [comment]
> 已经可以体验了 http://best-pay.springboot.cn
> 你也可以看看项目的源码

嗯嗯 调通了 谢谢廖师兄的指导
