### ISSUE TITLE
支付寳沙箱测试地址配置有誤

### ISSUE THREAD

**Issue by wangjinhai555** [Pay-Group/best-pay-sdk#60]
/**
     * 沙箱测试
     */
    String ALIPAY_GATEWAY_OPEN_DEV     = "https://openapi.alipaydev.com/gateway.do";
 /**
     * 沙箱测试
     */
    String ALIPAY_GATEWAY_OPEN_DEV     = "https://openapi.alipaydev.com";

多了一級

**Comment by lly835** [comment]
已修改 https://github.com/Pay-Group/best-pay-sdk/commit/ade9ef3b319d305f86b9f6cf7db79f4fb1de4aac
