### ISSUE TITLE
无法添加Maven依赖

### ISSUE THREAD

**Issue by kzysure** [Pay-Group/best-pay-sdk#7]
添加文档中的maven依赖后依旧无法找到对应依赖。
<img width="847" alt="2017-11-19 2 35 12" src="https://user-images.githubusercontent.com/24382306/32988080-0b7ca1ca-cd37-11e7-913e-72a0e77d34e3.png">

**Comment by idDaGouZzz** [comment]
你的是怎么解决的？我的也是maven无法依赖。

**Comment by idDaGouZzz** [comment]
依赖如果无法添加的话，先把本地的仓库的best-pay-sdk依赖删除了，重新依赖一下就ok了，多试几次。

**Comment by ralapchi** [comment]
我也是，请问你弄好了吗

**Comment by lly835** [comment]
用新版本
https://github.com/Pay-Group/best-pay-sdk/releases/tag/1.3.0.BETA

**Comment by samwuu** [comment]
aliyun的maven提示没有找到相应sdk 怎么解决

**Comment by samwuu** [comment]
aliyun的maven提示没有找到相应sdk 怎么解决

Failure to find cn.springboot:best-pay:pom:1.3.0.BETA in http://maven.aliyun.com/nexus/content/groups/public/ was cached in the local repository,

**Comment by lly835** [comment]
阿里云镜像同步，需要时间




| |
廖师兄
|
|
邮箱：lly835@163.com
|

签名由 网易邮箱大师 定制

在2019年10月18日 14:06，SamWuu 写道：

aliyun的maven提示没有找到相应sdk 怎么解决

Failure to find cn.springboot:best-pay:pom:1.3.0.BETA in http://maven.aliyun.com/nexus/content/groups/public/ was cached in the local repository,
