### ISSUE TITLE
支付宝异步返回结果的验签不通过的bug

### ISSUE THREAD

**Issue by xiongmaoshouzha** [Pay-Group/best-pay-sdk#74]
版本 1.3.1
源码中处理异步回调时，先把数据URLDecoder，再调用MapUtil.form2Map，

实际调用时，发现支付宝返回的签名(sign)上有“**=**”这样的字符串，form2Map方法里面，有按照“**=**”切割的代码，转换为map的签名少了“**=**”，导致签名验证失败

建议先按“&”分割，再URLDecoder

**Comment by wangjinhai555** [comment]
可以通过   我的项目目前使用的好着呢   商户私钥，支付宝公钥

**Comment by xiongmaoshouzha** [comment]
> 可以通过 我的项目目前使用的好着呢 商户私钥，支付宝公钥
跟签名有关，我测试的地址，支付宝给我的签名结尾有一个=，然后转换map的时候签名的值会漏掉，
比如说像这样 http://aaa.com?sign=xxxx=&sign_type=RSA2，form2Map转换后，sign就少了=

**Comment by xixingya** [comment]
我也有这个bug，一直签名校验失败

**Comment by lly835** [comment]
http://best-pay.springboot.cn/
这演示站点用着没问题


 原始邮件 
发件人: xixingya<notifications@github.com>
收件人: Pay-Group/best-pay-sdk<best-pay-sdk@noreply.github.com>
抄送: Subscribed<subscribed@noreply.github.com>
发送时间: 2020年9月22日(周二) 14:29
主题: Re: [Pay-Group/best-pay-sdk] 支付宝异步返回结果的验签不通过的bug (#74)


我也有这个bug，一直签名校验失败

**Comment by xixingya** [comment]
> http://best-pay.springboot.cn/ 这演示站点用着没问题 原始邮件 发件人: xixingya<notifications@github.com> 收件人: Pay-Group/best-pay-sdk<best-pay-sdk@noreply.github.com> 抄送: Subscribed<subscribed@noreply.github.com> 发送时间: 2020年9月22日(周二) 14:29 主题: Re: [Pay-Group/best-pay-sdk] 支付宝异步返回结果的验签不通过的bug (#74) 我也有这个bug，一直签名校验失败 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

因为签名问题，您看一下最上面那个回复，=造成的bug，我今天也遇到了

**Comment by lly835** [comment]
@xiongmaoshouzha @xixingya bug已修复。 
https://github.com/Pay-Group/best-pay-sdk/releases/tag/f2e3582
