### ISSUE TITLE
请问支付宝支付宝支持直接返回跳转链接么？而不是form

### ISSUE THREAD

**Issue by kanganxi** [Pay-Group/best-pay-sdk#75]

**Comment by lly835** [comment]
不行的。你可以去看支付宝的api


 原始邮件 
发件人: 康安喜<notifications@github.com>
收件人: Pay-Group/best-pay-sdk<best-pay-sdk@noreply.github.com>
抄送: Subscribed<subscribed@noreply.github.com>
发送时间: 2019年12月23日(周一) 19:52
主题: [Pay-Group/best-pay-sdk] 请问支付宝支付宝支持直接返回跳转链接么？而不是form (#75)

**Comment by kanganxi** [comment]
好的，谢谢！

**Comment by kanganxi** [comment]
> 不行的。你可以去看支付宝的api 原始邮件 发件人: 康安喜<notifications@github.com> 收件人: Pay-Group/best-pay-sdk<best-pay-sdk@noreply.github.com> 抄送: Subscribed<subscribed@noreply.github.com> 发送时间: 2019年12月23日(周一) 19:52 主题: [Pay-Group/best-pay-sdk] 请问支付宝支付宝支持直接返回跳转链接么？而不是form (#75) — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
感谢师兄回复，谢谢，学习了
