### ISSUE TITLE
微信native支付订单待支付的情况下出现的问题

### ISSUE THREAD

**Issue by jaymie9019** [Pay-Group/best-pay-sdk#83]
老师，您好 
<xml><return_code><![CDATA[SUCCESS]]></return_code>
<return_msg><![CDATA[OK]]></return_msg>
<appid><![CDATA[wx9e1e3dce3b609d08]]></appid>
<mch_id><![CDATA[1543623501]]></mch_id>
<device_info><![CDATA[]]></device_info>
<nonce_str><![CDATA[gNdSBWNJe4x0PNvX]]></nonce_str>
<sign><![CDATA[F68F01E5C68F6A5EC2245A903CA4E2E3]]></sign>
<result_code><![CDATA[SUCCESS]]></result_code>
<total_fee>1</total_fee>
<out_trade_no><![CDATA[701995330441969664]]></out_trade_no>
<trade_state><![CDATA[NOTPAY]]></trade_state>
<trade_state_desc><![CDATA[订单未支付]]></trade_state_desc>
</xml>

返回的xml格式中没有 time_end 字段

所以这个方法会报错
return OrderQueryResponse.builder()
                .orderStatusEnum(OrderStatusEnum.findByName(response.getTradeState()))
                .resultMsg(response.getTradeStateDesc())
				.outTradeNo(response.getTransactionId())
                .orderId(response.getOutTradeNo())
				.attach(response.getAttach())
                //yyyyMMddHHmmss -> yyyy-MM-dd HH:mm:ss
                .finishTime(response.getTimeEnd().replaceAll("(\\d{4})(\\d{2})(\\d{2})(\\d{2})(\\d{2})(\\d{2})", "$1-$2-$3 $4:$5:$6"))
                .build();

response.getTimeEnd().replaceAll("(\\d{4})(\\d{2})(\\d{2})(\\d{2})(\\d{2})(\\d{2})", "$1-$2-$3 $4:$5:$6")

**Comment by lly835** [comment]
你用最新的代码

**Comment by jaymie9019** [comment]
好的 谢谢
