### ISSUE TITLE
MAC 系统开发,找不到证书的问题

### ISSUE THREAD

**Issue by nanxiangqingfeng** [Pay-Group/best-pay-sdk#93]
```
public class WxPayConfig extends PayConfig {
  ........
        FileInputStream inputStream = null;

        try {
            inputStream = new FileInputStream(new File(this.keyPath));
        } catch (IOException var11) {
            throw new RuntimeException("读取微信商户证书文件出错", var11);
        }

```

此处,使用 File 读取文件,可能会出错
建议修改为:
```
public class WxPayConfig extends PayConfig {
  
        InputStream inputStream = null;

        try {
            ClassPathResource classPathResource = new ClassPathResource(this.keyPath);

            inputStream = classPathResource.getInputStream();
        } catch (IOException var11) {
            throw new RuntimeException("读取微信商户证书文件出错", var11);
        }

```

**Comment by lly835** [comment]
要写绝对路径




在2020年03月24日 13:20，王昊 写道：

public class WxPayConfig extends PayConfig {

  ........

        FileInputStream inputStream = null;



        try {

            inputStream = new FileInputStream(new File(this.keyPath));

        } catch (IOException var11) {

            throw new RuntimeException("读取微信商户证书文件出错", var11);

        }





此处,使用 File 读取文件,可能会出错
建议修改为:

public class WxPayConfig extends PayConfig {

  

        InputStream inputStream = null;



        try {

            ClassPathResource classPathResource = new ClassPathResource(this.keyPath);



            inputStream = classPathResource.getInputStream();

        } catch (IOException var11) {

            throw new RuntimeException("读取微信商户证书文件出错", var11);

        }

**Comment by nanxiangqingfeng** [comment]
但是我觉得这种方式反而更舒服,只写相对 resource (/)的路径就可以了

**Comment by nanxiangqingfeng** [comment]
我在尝试修改你的代码并重新打包,哈哈

**Comment by lly835** [comment]
证书不应该放项目里。尤其是生产环境的证书，属于敏感信息，不能让开发人员获取到




在2020年03月24日 13:25，王昊 写道：

我在尝试修改你的代码并重新打包,哈哈

**Comment by nanxiangqingfeng** [comment]
话是不假,但是小公司,后台就我一个人,就很难受啊

**Comment by lly835** [comment]
生产环境证书放在项目里，开发机器上就可以使用，太不安全了。
